config/routes.rb
Rails.application.routes.draw do
  get 'comment/index'
  get 'comment/create'
  get 'comment/new'
  # get '/home', to: 'static_pages#home'  
  # get '/gossips/:id', to: 'gossips#show', as: 'show'
  # get '/author/:id', to: 'author#show', as: 'author'


  # Pages statiques
  get '/team', to: 'static_pages#team'  
  get '/contact',to: 'static_pages#contact'  

  # Autres pages un peu solo à changer plus tard
  get '/welcome/:first_name', to: 'welcome#first_name'

  # REST & CRUD : 7 routes crées avec le resources
  resources :gossips do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  resources :authors,  only: [:index, :show] 
  resources :cities, only: [:show] 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, presence: true, length: { in: 3..14 }
  validates :content, presence: true
  belongs_to :user
  has_many :join_table_gossip_tags
  has_many :tags, through: :join_table_gossip_tags
  has_many :comments
end

app/models/join_table_gossip_tag.rb
class JoinTableGossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_table_gossip_tags
  has_many :gossips, through: :join_table_gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :error, :info, :danger, :warning
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = User.all
  end

  def show
    @author = User.find(params[:id])
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
      @comment = Comment.new(comment_params)
      @comment.user = User.create(first_name:"Thomas", last_name:"Laneyrie",description:"Si chaud today", email:"toto@gmail.com", age:33, city:City.first)
      @comment.save
      redirect_to gossip_path(@comment.gossip)
  end

  def new
    @comment = Comment.create
  end

  def edit
    @comment = Comment.find(params[:id])
    @gossip = Gossip.find(params[:gossip_id])
  end

  def update
    @comment = Comment.find(params[:id])    
    @gossip = Gossip.find(params[:gossip_id])  
    @comment.update(comment_params) 
    redirect_to gossip_path(@gossip)
  end

  def comment_params
    params.require(:comment).permit(:content).merge(gossip_id: params[:gossip_id])
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to gossip_path(@comment.gossip)
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def index 
    @gossips = Gossip.all
    @comment = Comment.create
  end 
  
  def show
    @gossip= Gossip.find(params[:id])
  end

  def new
    @gossip = Gossip.create
  end

  def create
    @gossip = Gossip.new(title:params["title"], content:params["content"], user: User.create(first_name:"Thomas", last_name:"Laneyrie",description:"Si chaud today", email:"toto@gmail.com", age:33, city:City.first))
    if @gossip.save
      redirect_to gossip_path(@gossip), success: 'Le Gossip a été créé avec succès'
    else 
      redirect_to new_gossip_path, danger: 'Echec dans la création du Gossip, essaye encore'
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
      @gossip = Gossip.find(params[:id])
      if @gossip.update(post_params)  
        redirect_to gossip_path(@gossip.id)
      else
        render :edit
      end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path
end
end

private
def post_params
  params.require(:gossip).permit(:title,:content) 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/authors/index.html.erb

<header>
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
  <center>
    <h1 class="display-4">Nos écervelés d'auteurs</h1>
    <h4>Ici, tu trouveras la liste de tous les teuteus qui ont balancé des cochonneries !</h4>
    <br>
    <br>
    <br>
    <h5>Les voici : </h5>  
    </center>
  </div>
</div>
<body>
<br>
</header>

<div class="m-4"></div>
  <div class="container border border-secondary"> 
    <div class="row border border-secondary fw-bold">
        <div class="col-5">Le gogole</div>    
        <div class="col-5">Sa ville</div>         
        <div class="col-2">Nombre de cochonneries</div>
    </div>


    <% @authors.each_with_index do |author, index| %> 
                          
        <div class="row border border-light">
            <div class="col-5"><a href= "<%=author_path(author.id)%>"><%=author.first_name%> <%=author.last_name%></a></div>            
            <div class="col-5"><a href= "<%=city_path(author.city.id)%>"><%=author.city.name%></a></div>
            <div class="col-2"><%=author.gossips.count%></div>         
        </div>

    <% end %>
  </div>

  <div class="list-group">
  <a href="#" class="list-group-item list-group-item-action list-group-item-light">Liste des auteurs</a>

  <% @authors.each_with_index do |author, index| %> 
    <a href="#" class="list-group-item list-group-item-action list-group-item-light"> Auteur <%=index%> : <%=author.first_name%> <%=author.last_name%>     -    <%=author.gossips.count%> Gossips    -     Ville d'origine : <%=author.city.name%></a>
  <% end %>

app/views/authors/show.html.erb
<center>


<header>
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
  <center>
    <h1 class="display-4">Mais qui est ce relou qui à pondu ça?</h1>
    <h5>Le voici : </h5>  
    </center>
  </div>
</div>
<body>
<br>
</header>


<h3>L'auteur en question : <%=@author.first_name%> <%= @author.last_name %></h3>
  <p>Sa bio : <%=@author.description%></p>
  <p>Tu veux t'expliquer avec ? : <%=@author.email%></p>
  <p>Nombre de balais : <%=@author.age%></p>
  <p> Sa ville : <a href= "<%=city_path(@author.city.id)%>"><%=@author.city.name%></a></p>     
  <p>Nombre de vomis : <%= @author.gossips.count %> </p>


<br>
<h4>Retrouves tous ses potins :<% @author.gossips.each do |gossip| %></h4>

  <p> <%=gossip.title%> -> <%= link_to "clique ici ducon", gossip_path(gossip) %>  </p>
</ul>
<% end %>
</center>

app/views/cities/show.html.erb
<div class="m-2">
  <h3>Sur cette page vous trouverez les gossips des auteurs qui viennent de chez nous!</h3>

  <% @city.users.each do |user| %>
    <p>Potins de <%=user.first_name%> <%=user.last_name%> :</p>
    <%user.gossips.each do |gossip| %>
      <ul><li>Potin : <a href= "<%=gossip_path(gossip.id)%>"><%=gossip.title%></a></li></ul>     
    <% end %>
  <% end %>
</div>

app/views/comments/_comment.html.erb
<article>
  <p>
    <small>De <%=comment.user.first_name%> <%=comment.user.last_name%> </small>:&nbsp;&nbsp <%= comment.content %>
   
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp
    <a href= "<%= edit_gossip_comment_path(@gossip,comment)%>">Editer</a>

  </p>
  <hr />
</article>

app/views/comments/_form.html.erb
<form action ="<%= gossip_comments_path(gossip)%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <textarea name ="comment[content]" rows="8" cols="40"></textarea>
  <p><input type="submit" value="Ajouter un commentaire" class ="btn btn-warning"></p>
</form>


app/views/comments/edit.html.erb
<%= form_for [@gossip, @comment] do |f| %>                                  
    <div class="form-group"> 
        <label>Contenu du commentaire</label> 
        <%= f.text_area :content, class: 'form-control' %>      
    </div>                                                      
    <div class="form-group">
        <button type ="submit">Modifier le commentaire</button>
    </div>

    <%= button_to "Supprimer le commentaire", gossip_comment_url(@gossip,@comment), method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-danger" %>

<% end %>

app/views/gossips/edit.html.erb
<div class="m-2">
  <h1> Edition d'un Gossip ! </h1>
</div>
  <p> id du gossip : <%= @gossip.id %>
  <%= form_for @gossip do |f| %>
      <div class="form-group">
          <label>Titre du Gossip</label>
          <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group"> 
          <label>Contenu du Gossip</label> 
          <%= f.text_area :content, class: 'form-control' %>            
      </div>
      
      </div>
      <div class="form-group">
          <button type ="submit">Modifier l'article</button>
      </div>
  <% end %>

app/views/gossips/index.html.erb
  <header>
  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <div class="container">
    <center>
      <h1 class="display-4">THE FUCKING GOSSIP PROJECT BY THP</h1>
      <h3>Bienvenue à toi la mocheté !!!</h3>
      <img src="https://images.uncyc.org/pt/thumb/2/26/4697.jpg/200px-4697.jpg">
      <h4>Ici, c'est carte blanche, on va voir à quel point tu aimes balancer des cochonneries !</h4>
      <br>
      <h5>Voici les dernières dégueulasseries : </h5>  
      </center>
    </div>
  </div>

  <body>
  <br>
  </header>

    <body>
    <div class="row m-1">
      <% @gossips.each_with_index do |gossip, index| %>
        <div class = "col d-flex align-items-top">
          <div class="card mb-3 p-3" style="width: 20rem;">
            <div class="card-body">
              <h5 class="card-title">Fucking gossip <%= index + 1%> : "<%= gossip.title %>"</h5>
              <p class="card-text ">Gogole : <%= gossip.user.first_name %> <%= gossip.user.last_name %></p>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">Date de création : <br/> <%= gossip.created_at.strftime("%d-%m-%y -%H:%M:%S") %></li>
                <li class="list-group-item">Nombre de merdes qu'il a créé : <%= gossip.user.gossips.count %></li>
                <li class="list-group-item">Nombre de commentaires sur cette connerie : <%= gossip.comments.count %></li>
                <p> </p>
              </ul>
            <div class="btn btn-warning">
                <%= link_to "Détail du potin", gossip_path(gossip), style: 'color:black' %>
            </div>
          </div>
        </div>
    </div>
      <% end %>
  </div>
</body>

app/views/gossips/index_new_in_progress.html.erb
<body>

<h2> Bienvenue à la page d'accueil du Gossip Project </h2><br/>

<div class="container-fluid">
  <div class="row border border-danger">
      <div class="col-2 border border-success">Potin titre</div>
      <div class="col-6">Auteur</div>
      <div class="col-4 border border-success">Potin contenu</div>
  </div>
</div>
<br><br><br>




<% @gossips.each_with_index do |gossip, index| %>
  <p>Potin <%= index + 1%> : "<%= gossip.title %>"</p>
  <p>Auteur : <%= gossip.user.first_name %> <%= gossip.user.last_name %></p>
  <p><%= gossip.created_at.strftime("%d-%m-%y %H:%M:%S") %></p>
  <p><%= gossip.user.gossips.count %></p>
  <p><%= link_to "Le gossip en détails", gossip_path(gossip), style: 'color:white' %></p>
<% end %>

</body>

app/views/gossips/new.html.erb
<header>
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
  <center>
    <h1 class="display-4">Balances ta connerie!</h1>
    <h3>Fais toi plaisir nunuche, ça doit pas t'arriver souvent</h3>
    </center>
  </div>
</div>
<body>

<center>
<% flash.each do |name, msg| %>
  <div class="alert alert-danger" role="alert"> <%= msg %> </div>
<% end %>

<%# Form_tag %>
<%= form_tag url_for(action: 'create'), method: "post" do %>

  <%= label_tag 'Fucking title :' %>
  <%= text_field_tag 'title', @gossip.title %>
  <br /> <br />

  <%= label_tag 'Son contenu :' %>
  <%= text_field_tag 'content', @gossip.content %>
  <br /> <br />

  <%= submit_tag "Création d'une nouvelle daube" %>
<% end %>
<br>
<br>
<img src="https://koureisya-blog.info/wp-content/uploads/2017/08/kot-2508858_1280-246x200.jpg">
</center>

</header>

app/views/gossips/show.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-success" role="alert"> <%= msg %> </div>
<% end %>

<h1>Connerie N°<%= @gossip.id %> </h1>
<p>Créé le : <%= @gossip.created_at %></p>
<p>Son foutu titre : <%= @gossip.title %></p>
<p>Le gogole en question : <%= @gossip.user.first_name %> <%= @gossip.user.last_name %></p>
<p>Sa ville : <a href= "<%=city_path(@gossip.user.city.id)%>"><%=@gossip.user.city.name%></a></p>     
<p>Plus d'infos ? <%= link_to "Cliquer ici", author_path(@gossip.user.id) %></p>
<p>Contenu du merdier : <%= @gossip.content %></p>

<%= button_to "Supprimer cette merde", gossip_path(@gossip.id), method: :delete, data: { confirm: "T'es sur de toi mon salop?" }, class:"btn btn-danger" %>
<br>

<h2>Balance ton com !</h2>

<h4> Commentaires :</h4>
<%= render @gossip.comments %>
<%= render partial: 'comments/form', locals: { gossip: @gossip } %>


app/views/static_pages/contact.html.erb

<header>
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
  <center>
    <h1 class="display-4">Comment nous contacter?</h1>
    <h4>C'est tout simple nunuche, tu remplies le formulaire (tu sais celui que tu vois si tu baisses les yeux), et si on a le temps et la motivation, on te recontacte dans des délais abérrants ! Eh oui, on s'en tape le coquillard !</h4>
    </center>
    <br>
  </div>
</div>
<body>
</header>

<head>
    <title>Formulaire de contact</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
    <link href='custom.css' rel='stylesheet' type='text/css'>
</head>
 
<body>
 
    <div class="container">
 
        <div class="row">
 
            <div class="col-xl-8 offset-xl-2 py-5">
 
                <h1>Formulaire de contact pour gogoles</h1>
 
                <p class="lead">Tu as réussi à baisser les yeux? Eh ben voilà comment nous contacter</p>
 
 
                <form id="contact-form" method="post" action="contact.php" role="form">
 
                    <div class="messages"></div>
 
                    <div class="controls">
 
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="form_name">Nom *</label>
                                    <input id="form_name" type="text" name="name" class="form-control" placeholder="Veuillez entrer votre nom *" required="required" data-error="Nom est obligatoire.">
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="form_lastname">Prénom *</label>
                                    <input id="form_lastname" type="text" name="surname" class="form-control" placeholder="Veuillez entre votre prénom *" required="required" data-error="Prénom est obligatoire.">
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="form_email">Email *</label>
                                    <input id="form_email" type="email" name="email" class="form-control" placeholder="Veuillez entrer votre email *" required="required" data-error="Un email valid est obligatoire.">
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="form_need">Veuillez préciser votre besoin *</label>
                                    <select id="form_need" name="need" class="form-control" required="required" data-error="Veuillez préciser votre besoin.">
                                        <option value=""></option>
                                        <option value="Demande de devis">Demande de devis</option>
                                        <option value="Demande générale">Demande générale</option>
                                        <option value="Demander une facture">Demander une facture</option>
                                        <option value="Autre">Autre</option>
                                    </select>
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="form_message">Message *</label>
                                    <textarea id="form_message" name="message" class="form-control" placeholder="Votre Message *" rows="4" required="required" data-error="Veuillez remplir le champ Message."></textarea>
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <input type="submit" class="btn btn-success btn-send" value="Envoyer">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <p class="text-muted">
                                    <strong>*</strong> Ces champs sont obligatoires.</p>
                            </div>
                        </div>
                    </div>
 
                </form>
 
            </div>
            <!-- /.8 -->
 
        </div>
        <!-- /.row-->
 
    </div>
    <!-- /.container-->
 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.11.9/validator.min.js" crossorigin="anonymous"></script>
    <script src="contact.js"></script>
</body>

app/views/static_pages/team.html.erb

<header>
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
  <center>
    <h1 class="display-4">LA TEAM CROQUETTE</h1>
    <h3>Voici notre belle équipe de glandeurs (on adore se toucher la nouille)</h3>
    </center>
  </div>
</div>
<body>
</header>


<center>
<h3>Tom-tom</h3>
<h5>La tête du groupe, une voix sexy, une belle intelligence, si t'es sapio-sexuel il est pour toi!</h5>
<br>
<br>
<br>
<br>
<h3>Samuelito</h3>
<h5>Energie débordante et blagues du moyen-âge, une bonne poire !</h5>
<a href="https://zupimages.net/viewer.php?id=23/07/c868.jpg"><img src="https://zupimages.net/up/23/07/c868.jpg" alt="" /></a>
<br>
<br>
<br>
<br>
<h3>La belle Isabelle</h3>
<h5>Adores la télé réalité, se faire les ongles, et montrer ses pieds</h5>
<a href="https://zupimages.net/viewer.php?id=23/07/p5ep.jpg"><img src="https://zupimages.net/up/23/07/p5ep.jpg" alt="" /></a>
<br>
<br>
<br>
<br>
<h3>Andreanounette</h3>
<h5>Celle qui réfléchis vraiment, il en fallait bien une !</h5>
<a href="https://zupimages.net/viewer.php?id=23/07/lwng.jpg"><img src="https://zupimages.net/up/23/07/lwng.jpg" alt="" /></a>
<br>
<br>
<br>
<br>
<h3>Zitouninou</h3>
<h5>Le sang de la veine, le frérot, le J c'est le S</h5>
<a href="https://zupimages.net/viewer.php?id=23/07/gfqw.jpg"><img src="https://zupimages.net/up/23/07/gfqw.jpg" alt="" /></a>
<br>
<br>
<br>
<br>
<h3>Yaya alias choupinou</h3>
<h5>Beau, intelligent, charismatique, que dire de plus?</h5>
<a href="https://zupimages.net/viewer.php?id=23/07/jijk.jpg"><img src="https://zupimages.net/up/23/07/jijk.jpg" alt="" /></a>
</center>

app/views/welcome/first_name.html.erb
<h1>Welcome#show</h1>

<p> Bienvenue <%= params[:first_name] %> !! </p>