config/routes.rb
Rails.application.routes.draw do
  get 'comment/index'
  get 'comment/create'
  get 'comment/new'
  # get '/home', to: 'static_pages#home'  
  # get '/gossips/:id', to: 'gossips#show', as: 'show'
  # get '/author/:id', to: 'author#show', as: 'author'


  # Pages statiques
  get '/team', to: 'static_pages#team'  
  get '/contact',to: 'static_pages#contact'  

  # Autres pages un peu solo à changer plus tard
  get '/welcome/:first_name', to: 'welcome#first_name'

  # REST & CRUD : 7 routes crées avec le resources
  resources :gossips do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  resources :authors,  only: [:index, :show] 
  resources :cities, only: [:show] 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, presence: true, length: { in: 3..14 }
  validates :content, presence: true
  belongs_to :user
  has_many :join_table_gossip_tags
  has_many :tags, through: :join_table_gossip_tags
  has_many :comments
end

app/models/join_table_gossip_tag.rb
class JoinTableGossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_table_gossip_tags
  has_many :gossips, through: :join_table_gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :error, :info, :danger, :warning
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = User.all
  end

  def show
    @author = User.find(params[:id])
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
      @comment = Comment.new(comment_params)
      @comment.user = User.create(first_name:"Thomas", last_name:"Laneyrie",description:"Si chaud today", email:"toto@gmail.com", age:33, city:City.first)
      @comment.save
      redirect_to gossip_path(@comment.gossip)
  end

  def new
    @comment = Comment.create
  end

  def edit
    @comment = Comment.find(params[:id])
    @gossip = Gossip.find(params[:gossip_id])
  end

  def update
    @comment = Comment.find(params[:id])    
    @gossip = Gossip.find(params[:gossip_id])  
    @comment.update(comment_params) 
    redirect_to gossip_path(@gossip)
  end

  def comment_params
    params.require(:comment).permit(:content).merge(gossip_id: params[:gossip_id])
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to gossip_path(@comment.gossip)
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def index 
    @gossips = Gossip.all
    @comment = Comment.create
  end 
  
  def show
    @gossip= Gossip.find(params[:id])
  end

  def new
    @gossip = Gossip.create
  end

  def create
    @gossip = Gossip.new(title:params["title"], content:params["content"], user: User.create(first_name:"Thomas", last_name:"Laneyrie",description:"Si chaud today", email:"toto@gmail.com", age:33, city:City.first))
    if @gossip.save
      redirect_to gossip_path(@gossip), success: 'Le Gossip a été créé avec succès'
    else 
      redirect_to new_gossip_path, danger: 'Echec dans la création du Gossip, essaye encore'
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
      @gossip = Gossip.find(params[:id])
      if @gossip.update(post_params)  
        redirect_to gossip_path(@gossip.id)
      else
        render :edit
      end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path
end
end

private
def post_params
  params.require(:gossip).permit(:title,:content) 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProjectNew</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> 
    <%# <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %> 
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

<header> 
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">FUCKING GOSSIP PROJECT</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav mr-auto">
        <li>
          <a class="nav-link" <%= link_to "Home", gossips_path %> </a>
        </li>
        <li>
          <a class="nav-link" <%= link_to "La team Croquette", team_path %> </a> 
        </li>
        <li>
          <a class="nav-link" <%= link_to "Nous contacter", contact_path %> </a>    
        </li>
        <li>
          <a class="nav-link" <%= link_to "Les foutus auteurs", authors_path %> </a>    
        </li>
        <li>
          <a class="nav-link" <%= link_to "Envoyer un potin !", new_gossip_path %> </a>    
        </li>
      </ul>
    </div>
  </nav>
</header>

  <body data-turbo-disabled="true">
    <%= yield %>
  </body>
</html>